# Generated by Django 6.0 on 2025-12-10 00:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional profile photo for the employee.', null=True, upload_to=accounts.models.employee_photo_upload_path),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image for this shop (used in UI).', null=True, upload_to=accounts.models.shop_logo_upload_path),
        ),
    ]
