# Generated by Django 6.0 on 2025-12-08 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_inventory', models.BooleanField(default=True)),
                ('enable_analytics', models.BooleanField(default=True)),
                ('enable_time_tracking', models.BooleanField(default=True)),
                ('enable_assistants', models.BooleanField(default=True)),
                ('default_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Default hourly rate for time-based cost calculations.', max_digits=10, null=True)),
                ('default_project_priority', models.CharField(blank=True, help_text="Optional default priority label (e.g. 'normal', 'rush').", max_length=20)),
                ('working_hours', models.JSONField(blank=True, help_text='Optional structured working hours config per weekday.', null=True)),
                ('locale', models.CharField(blank=True, help_text="Optional locale (e.g. 'en-US') for formatting.", max_length=20)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'Shop configuration',
                'verbose_name_plural': 'Shop configurations',
            },
        ),
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('etsy', 'Etsy'), ('shopify', 'Shopify'), ('square', 'Square'), ('stripe', 'Stripe'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=50)),
                ('name', models.CharField(help_text="Short label for this integration (e.g. 'Main Etsy shop').", max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('credentials', models.JSONField(blank=True, help_text='Secure-ish storage for tokens/keys (later move to vault or env).', null=True)),
                ('settings', models.JSONField(blank=True, help_text='Provider-specific options (e.g. shop IDs, sync settings).', null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='accounts.shop')),
            ],
            options={
                'ordering': ['shop', 'provider', 'name'],
                'unique_together': {('shop', 'provider', 'name')},
            },
        ),
    ]
