# Generated by Django 6.0 on 2025-12-20 16:08

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('projects', '0001_initial'), ('projects', '0002_initial'), ('projects', '0003_project_photo'), ('projects', '0004_project_station'), ('projects', '0005_project_product_template')]

    dependencies = [
        ('accounts', '0001_initial'),
        ('accounts', '0002_employee_photo_shop_logo'),
        ('customers', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('reference_code', models.CharField(blank=True, help_text='Optional short code used internally or on tickets/invoices.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('rush', 'Rush')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Optional initial estimate of total project hours.', max_digits=7, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Aggregated tracked hours (to be populated later by time tracking).', max_digits=7, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='accounts.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to='accounts.employee')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_in_stage', to='workflows.workflowstage')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='customers.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.shop')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='workflows.workflow')),
                ('photo', models.ImageField(blank=True, help_text='Optional photo of the project.', null=True, upload_to=projects.models.project_photo_upload_path)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.station')),
            ],
            options={
                'ordering': ['shop', '-created_at'],
            },
        ),
    ]
