# Generated by Django 6.0 on 2025-12-10 00:11

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo of the project.', null=True, upload_to=projects.models.project_photo_upload_path),
        ),
    ]
