# Generated by Django 6.0 on 2025-12-18 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_photo_shop_logo'),
        ('projects', '0003_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.station'),
        ),
    ]
