# Generated by Django 6.0 on 2025-12-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producttemplate_photo_projectpromotion_image'),
        ('projects', '0004_project_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product_template',
            field=models.ForeignKey(blank=True, help_text='Optional source ProductTemplate used to create this project (provenance).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='products.producttemplate'),
        ),
    ]
