# Generated by Django 6.0 on 2025-12-21 03:45

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_consumable_image_equipment_image_material_image'),
        ('products', '0003_alter_producttemplate_base_price_and_more'),
        ('projects', '0006_project_product_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.project_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='product_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='products.producttemplate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reference_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectConsumableSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumable_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.consumable')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_snapshots', to='projects.project')),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producttemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectEquipmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_snapshots', to='projects.project')),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producttemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_snapshots', to='projects.project')),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producttemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
