# Generated by Django 6.0 on 2025-12-08 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='If true, this is the default workflow for new projects in this shop.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to='accounts.employee')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='accounts.shop')),
            ],
            options={
                'ordering': ['shop', 'name'],
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Stage order within the workflow (lower = earlier).')),
                ('is_initial', models.BooleanField(default=False, help_text='If true, this can be used as a starting stage for new projects.')),
                ('is_final', models.BooleanField(default=False, help_text="If true, this represents a terminal stage (e.g. 'Completed').")),
                ('wip_limit', models.PositiveIntegerField(default=0, help_text='Optional WIP limit for this stage (0 = no limit).')),
                ('is_active', models.BooleanField(default=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflow')),
            ],
            options={
                'ordering': ['workflow', 'order', 'id'],
                'unique_together': {('workflow', 'name')},
            },
        ),
    ]
