# Generated by Django 6.0 on 2025-12-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='allows_sale_log',
            field=models.BooleanField(default=False),
        ),
    ]
