# Generated by Django 6.0 on 2025-12-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowstage_allows_sale_log'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='uniq_workflow_stage_order'),
        ),
    ]
