# Generated by Django 6.0 on 2025-12-08 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0002_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('etsy', 'Etsy'), ('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('other', 'Other')], default='etsy', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional per-promo title (e.g. Etsy listing title).', max_length=200)),
                ('link_url', models.URLField(blank=True, help_text='URL of the listing/post.')),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price before tax/fees.', max_digits=10, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Default estimated hours for this template.', max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_templates', to='workflows.workflow')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_templates', to='accounts.shop')),
            ],
            options={
                'ordering': ['shop', 'name'],
                'unique_together': {('shop', 'slug')},
            },
        ),
    ]
