# Generated by Django 6.0 on 2025-12-10 00:11

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional product template photo.', null=True, upload_to=products.models.product_template_photo_upload_path),
        ),
        migrations.AddField(
            model_name='projectpromotion',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional promo image or thumbnail.', null=True, upload_to=products.models.promotion_image_upload_path),
        ),
    ]
