# Generated by Django 6.0 on 2025-12-21 03:45

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_consumable_image_equipment_image_material_image'),
        ('products', '0002_producttemplate_photo_projectpromotion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='projectpromotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.promotion_image_upload_path),
        ),
        migrations.AlterField(
            model_name='projectpromotion',
            name='link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpromotion',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ProductTemplateConsumableRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_requirements', to='inventory.consumable')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_requirements', to='products.producttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplateEquipmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_requirements', to='inventory.equipment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requirements', to='products.producttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplateMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_requirements', to='inventory.material')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='products.producttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
