# Generated by Django 6.0 on 2025-12-08 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(help_text="e.g. 'project_created', 'order_paid'.", max_length=100)),
                ('source', models.CharField(blank=True, help_text='Optional event source label.', max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, help_text='Raw event payload or normalized properties.', null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='accounts.shop')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_key', models.CharField(help_text="Machine-readable metric key (e.g. 'daily_revenue').", max_length=100)),
                ('label', models.CharField(blank=True, help_text='Optional human-readable label.', max_length=200)),
                ('snapshot_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('extra', models.JSONField(blank=True, help_text='Optional structured metadata (dimensions, breakdowns, etc.).', null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='accounts.shop')),
            ],
            options={
                'ordering': ['shop', 'snapshot_date', 'metric_key'],
                'unique_together': {('shop', 'metric_key', 'snapshot_date')},
            },
        ),
    ]
