# Generated by Django 6.0 on 2025-12-08 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Optionally link a task to a workflow stage for finer-grained views.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_in_stage', to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='task',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.station'),
        ),
    ]
