# Generated by Django 6.0 on 2025-12-10 00:11

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional customer avatar or logo.', null=True, upload_to=customers.models.customer_photo_upload_path),
        ),
    ]
