# Generated by Django 6.0 on 2025-12-08 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, help_text='Optional internal or vendor SKU.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(blank=True, help_text="e.g. 'board ft', 'ml', 'pcs'.", max_length=50)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, help_text='Current quantity on hand.', max_digits=10)),
                ('reorder_point', models.DecimalField(decimal_places=3, default=0, help_text='Reorder threshold. 0 = no threshold.', max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Last known unit cost.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('consumable_type', models.CharField(blank=True, help_text="Optional consumable type label (e.g. 'Abrasive', 'Adhesive').", max_length=100)),
                ('preferred_station', models.ForeignKey(blank=True, help_text='Optional primary station where this item is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='accounts.station')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.shop')),
            ],
            options={
                'ordering': ['shop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, help_text='Optional internal or vendor SKU.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(blank=True, help_text="e.g. 'board ft', 'ml', 'pcs'.", max_length=50)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, help_text='Current quantity on hand.', max_digits=10)),
                ('reorder_point', models.DecimalField(decimal_places=3, default=0, help_text='Reorder threshold. 0 = no threshold.', max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Last known unit cost.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('preferred_station', models.ForeignKey(blank=True, help_text='Optional primary station where this item is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='accounts.station')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.shop')),
            ],
            options={
                'ordering': ['shop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, help_text='Optional internal or vendor SKU.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(blank=True, help_text="e.g. 'board ft', 'ml', 'pcs'.", max_length=50)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, help_text='Current quantity on hand.', max_digits=10)),
                ('reorder_point', models.DecimalField(decimal_places=3, default=0, help_text='Reorder threshold. 0 = no threshold.', max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Last known unit cost.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('material_type', models.CharField(blank=True, help_text="Optional material type label (e.g. 'Hardwood', 'Plywood', 'Resin').", max_length=100)),
                ('preferred_station', models.ForeignKey(blank=True, help_text='Optional primary station where this item is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='accounts.station')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.shop')),
            ],
            options={
                'ordering': ['shop', 'name'],
            },
        ),
    ]
