# Generated by Django 6.0 on 2025-12-10 00:11

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image or thumbnail for this inventory item.', null=True, upload_to=inventory.models.inventory_image_upload_path),
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image or thumbnail for this inventory item.', null=True, upload_to=inventory.models.inventory_image_upload_path),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image or thumbnail for this inventory item.', null=True, upload_to=inventory.models.inventory_image_upload_path),
        ),
    ]
