# Generated by Django 6.0 on 2025-12-21 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_photo_shop_logo'),
        ('inventory', '0002_consumable_image_equipment_image_material_image'),
        ('projects', '0007_alter_project_actual_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_type', models.CharField(choices=[('material', 'Material'), ('consumable', 'Consumable'), ('equipment', 'Equipment')], max_length=20)),
                ('bom_snapshot_type', models.CharField(blank=True, help_text='material | consumable | equipment', max_length=20)),
                ('bom_snapshot_id', models.PositiveIntegerField(blank=True, help_text='ID of the corresponding Project BOM snapshot', null=True)),
                ('quantity_delta', models.DecimalField(decimal_places=3, help_text='Negative = consume, positive = restock/adjust', max_digits=10)),
                ('reason', models.CharField(choices=[('consume', 'Consume'), ('adjustment', 'Adjustment'), ('waste', 'Waste'), ('return', 'Return')], default='consume', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.consumable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='accounts.employee')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.equipment')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.material')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='projects.project')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='accounts.shop')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='accounts.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
