# Generated by Django 6.0 on 2025-12-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(blank=True, help_text="Optional equipment type label (e.g. 'Power Tool', 'Machine', 'Hand Tool').", max_length=100),
        ),
    ]
