name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  backend:
    name: Backend tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        env:
          DJANGO_SETTINGS_MODULE: makerfex_backend.settings
        run: |
          pytest -q

  foundation_gate:
    name: Foundation gate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run foundation tests
        env:
          DJANGO_SETTINGS_MODULE: makerfex_backend.settings
        run: |
          pytest -m foundation -q
