# Generated by Django 6.0 on 2025-12-08 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('role_prompt', models.TextField(blank=True, help_text='System/role instructions for this assistant.')),
                ('default_model_name', models.CharField(blank=True, help_text="Optional default LLM identifier (e.g. 'gpt-5.1').", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(blank=True, help_text='If null, this assistant is global / shared.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='accounts.shop')),
            ],
            options={
                'ordering': ['shop__slug', 'name'],
                'unique_together': {('shop', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Optional user-facing title for this session.', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('closed', 'Closed')], default='active', max_length=20)),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='Timestamp of last message or interaction.', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Arbitrary session metadata (e.g. tags, context references).', null=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='assistants.assistantprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_sessions', to='accounts.employee')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_sessions', to='accounts.shop')),
            ],
            options={
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, help_text='Additional structured data (tool calls, tokens, etc.).', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistants.assistantsession')),
            ],
            options={
                'ordering': ['session', 'created_at', 'id'],
            },
        ),
    ]
